# Generated by Django 5.2.8 on 2026-01-26 14:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('period_start', models.DateField(verbose_name='Период с')),
                ('period_end', models.DateField(verbose_name='Период по')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлен'), ('approved', 'Утверждён'), ('paid', 'Оплачен')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_sheets', to=settings.AUTH_USER_MODEL, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Расчётный лист',
                'verbose_name_plural': 'Расчётные листы',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('hour', 'За час'), ('group', 'За группу')], max_length=10, verbose_name='Тип тарифа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='payroll.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='payroll.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['-effective_from', 'teacher'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Часы')),
                ('rate_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Тариф за час')),
                ('rate_per_group', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Тариф за группу')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='payroll_entries', to='payroll.group', verbose_name='Группы')),
                ('payroll_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.payrollsheet', verbose_name='Расчётный лист')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='payroll.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='payroll.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Запись в расчётном листе',
                'verbose_name_plural': 'Записи в расчётных листах',
                'ordering': ['date', 'teacher'],
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('period_start', models.DateField(verbose_name='Период с')),
                ('period_end', models.DateField(verbose_name='Период по')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='payroll.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Премиальные',
                'verbose_name_plural': 'Премиальные',
                'ordering': ['-period_start', 'teacher'],
            },
        ),
    ]
