# Generated by Django 5.2.8 on 2026-02-17 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollentry',
            name='groups',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
