# Generated by Django 5.2.8 on 2026-02-17 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-effective_from', 'subject'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.RemoveField(
            model_name='rate',
            name='teacher',
        ),
        migrations.AddField(
            model_name='payrollsheet',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='payroll_sheets', to='payroll.subject', verbose_name='Предметы по листу'),
        ),
        migrations.AddField(
            model_name='payrollsheet',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_sheets', to='payroll.teacher', verbose_name='Педагог (ФИО)'),
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_kind',
            field=models.CharField(choices=[('payment', 'Оплата'), ('bonus', 'Премиальные'), ('vacation', 'Отпускные')], default='payment', max_length=20, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('hour', 'За час'), ('group', 'За группу')], max_length=10, null=True, verbose_name='Тип (только для Оплаты)'),
        ),
    ]
