# Generated by Django 6.0.2 on 2026-03-01 12:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_rates_and_sheet_teacher_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_from', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Класс от')),
                ('class_to', models.IntegerField(default=11, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Класс до')),
                ('basic_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Основная цена')),
                ('premium_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Премиальные')),
                ('vacation_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Отпускные')),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Цена групповых занятий',
                'verbose_name_plural': 'Цены групповых занятий',
                'ordering': ['-effective_from', 'class_from'],
            },
        ),
        migrations.CreateModel(
            name='IndividualPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Основная цена')),
                ('premium_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Премиальные')),
                ('vacation_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Отпускные')),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Цена индивидуальных занятий',
                'verbose_name_plural': 'Цены индивидуальных занятий',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PkshPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Основная цена')),
                ('premium_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Премиальные')),
                ('vacation_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Отпускные')),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Цена ПКШ',
                'verbose_name_plural': 'Цены ПКШ',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AlterModelOptions(
            name='payrollentry',
            options={'ordering': ['date', 'teacher'], 'verbose_name': 'Запись в расчётном листе (устар.)', 'verbose_name_plural': 'Записи в расчётных листах (устар.)'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-effective_from', 'subject'], 'verbose_name': 'Тариф (устар.)', 'verbose_name_plural': 'Тарифы (устар.)'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='payroll.subject', verbose_name='Предметы'),
        ),
        migrations.AlterField(
            model_name='payrollsheet',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='payroll_sheets', to='payroll.subject', verbose_name='Предметы'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('hour', 'За час'), ('group', 'За группу')], max_length=10, null=True, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_type', models.CharField(choices=[('request', 'Запрос аванса'), ('payment', 'Выплата аванса')], max_length=20, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='payroll.payrollsheet', verbose_name='Расчётный лист')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='payroll.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Аванс',
                'verbose_name_plural': 'Авансы',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupLessonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=300, verbose_name='Состав группы')),
                ('children_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Детей в группе')),
                ('grade_class', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Класс')),
                ('is_pksh', models.BooleanField(default=False, verbose_name='ПКШ (подготовка к школе)')),
                ('lessons_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Занятий')),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Часов')),
                ('lesson_dates', models.TextField(blank=True, verbose_name='Даты занятий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_entries', to='payroll.payrollsheet', verbose_name='Расчётный лист')),
            ],
            options={
                'verbose_name': 'Групповое занятие',
                'verbose_name_plural': 'Групповые занятия',
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='IndividualLessonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200, verbose_name='ФИ ученика')),
                ('lessons_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Занятий')),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Часов')),
                ('lesson_dates', models.TextField(blank=True, verbose_name='Даты занятий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_entries', to='payroll.payrollsheet', verbose_name='Расчётный лист')),
            ],
            options={
                'verbose_name': 'Индивидуальное занятие',
                'verbose_name_plural': 'Индивидуальные занятия',
                'ordering': ['student_name'],
            },
        ),
    ]
