# Generated by Django 6.0.2 on 2026-03-01 13:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_groupprice_individualprice_pkshprice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['-period_start'], 'verbose_name': 'Премиальные', 'verbose_name_plural': 'Премиальные'},
        ),
        migrations.AlterModelOptions(
            name='payrollentry',
            options={'ordering': ['date'], 'verbose_name': 'Запись (устар.)', 'verbose_name_plural': 'Записи (устар.)'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-effective_from'], 'verbose_name': 'Тариф (устар.)', 'verbose_name_plural': 'Тарифы (устар.)'},
        ),
        migrations.RemoveField(
            model_name='grouplessonentry',
            name='is_pksh',
        ),
        migrations.AddField(
            model_name='advance',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает одобрения'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='payrollsheet',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма аванса'),
        ),
        migrations.AddField(
            model_name='payrollsheet',
            name='rejection_comment',
            field=models.TextField(blank=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='payrollsheet',
            name='total_basic',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Основные'),
        ),
        migrations.AddField(
            model_name='payrollsheet',
            name='total_premium',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Премиальные'),
        ),
        migrations.AddField(
            model_name='payrollsheet',
            name='total_vacation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Отпускные'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advance',
            name='advance_type',
            field=models.CharField(choices=[('request', 'Запрос аванса'), ('repayment', 'Погашение аванса')], max_length=20),
        ),
        migrations.AlterField(
            model_name='advance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='advance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='advance',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='advance',
            name='payroll_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='payroll.payrollsheet'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='payroll.teacher'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='period_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='period_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='payroll.teacher'),
        ),
        migrations.AlterField(
            model_name='grouplessonentry',
            name='children_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='grouplessonentry',
            name='grade_class',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Класс (0=ПКШ)'),
        ),
        migrations.AlterField(
            model_name='grouplessonentry',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='grouplessonentry',
            name='lesson_dates',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='grouplessonentry',
            name='lessons_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='grouplessonentry',
            name='payroll_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_entries', to='payroll.payrollsheet'),
        ),
        migrations.AlterField(
            model_name='individuallessonentry',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='individuallessonentry',
            name='lesson_dates',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='individuallessonentry',
            name='lessons_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='individuallessonentry',
            name='payroll_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_entries', to='payroll.payrollsheet'),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='payroll_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.payrollsheet'),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='rate_per_group',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='rate_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='payroll.subject'),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='payroll.teacher'),
        ),
        migrations.AlterField(
            model_name='payrollsheet',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollsheet',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payrollsheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлен'), ('approved', 'Утверждён'), ('rejected', 'Отклонён'), ('paid', 'Оплачен')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollsheet',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='payroll_sheets', to='payroll.subject'),
        ),
        migrations.AlterField(
            model_name='payrollsheet',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_sheets', to='payroll.teacher', verbose_name='Педагог'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='effective_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rate',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_kind',
            field=models.CharField(choices=[('payment', 'Оплата'), ('bonus', 'Премиальные'), ('vacation', 'Отпускные')], default='payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('hour', 'За час'), ('group', 'За группу')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='payroll.subject'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('payroll_credit', 'Начисление по ведомости'), ('disbursement', 'Выдача средств'), ('extra_credit', 'Дополнительное начисление'), ('advance_given', 'Аванс выдан'), ('advance_repaid', 'Аванс погашен')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('payroll_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payroll.payrollsheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Педагог'), ('administrator', 'Администратор'), ('accountant', 'Бухгалтер'), ('senior_admin', 'Старший администратор'), ('chief_admin', 'Главный администратор'), ('moderator', 'Модератор')], default='teacher', max_length=20, verbose_name='Роль')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='payroll.city', verbose_name='Город')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
