# Generated by Django 6.0.2 on 2026-03-01 13:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_city_alter_bonus_options_alter_payrollentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_type',
            field=models.CharField(choices=[('main', 'Основной'), ('premium', 'Премиальные'), ('vacation', 'Отпускные')], default='main', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollsheet',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollsheet',
            name='total_basic',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollsheet',
            name='total_premium',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollsheet',
            name='total_vacation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payroll_credit', 'Начисление по ведомости'), ('premium_credit', 'Начисление премиальных'), ('vacation_credit', 'Начисление отпускных'), ('disbursement', 'Выдача средств'), ('premium_disbursement', 'Выдача премиальных'), ('vacation_disbursement', 'Выдача отпускных'), ('extra_credit', 'Дополнительное начисление'), ('extra_premium', 'Дополнительные премиальные'), ('extra_vacation', 'Дополнительные отпускные'), ('advance_given', 'Аванс выдан'), ('advance_repaid', 'Аванс погашен'), ('expense', 'Расход'), ('income', 'Доход')], max_length=30),
        ),
    ]
