# Generated by Django 6.0.2 on 2026-03-01 14:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_transaction_balance_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advance',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['-period_start']},
        ),
        migrations.AlterModelOptions(
            name='grouplessonentry',
            options={'ordering': ['group_name']},
        ),
        migrations.AlterModelOptions(
            name='groupprice',
            options={'ordering': ['-effective_from', 'class_from']},
        ),
        migrations.AlterModelOptions(
            name='individuallessonentry',
            options={'ordering': ['student_name']},
        ),
        migrations.AlterModelOptions(
            name='individualprice',
            options={'ordering': ['-effective_from']},
        ),
        migrations.AlterModelOptions(
            name='payrollentry',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='payrollsheet',
            options={'ordering': ['-period_start', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pkshprice',
            options={'ordering': ['-effective_from']},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-effective_from']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA включена'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, verbose_name='2FA секрет'),
        ),
        migrations.AlterField(
            model_name='grouplessonentry',
            name='children_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grouplessonentry',
            name='grade_class',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='grouplessonentry',
            name='group_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='grouplessonentry',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='grouplessonentry',
            name='lessons_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupprice',
            name='basic_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='groupprice',
            name='class_from',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='groupprice',
            name='class_to',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='groupprice',
            name='effective_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='groupprice',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupprice',
            name='premium_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='groupprice',
            name='vacation_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='individuallessonentry',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='individuallessonentry',
            name='lessons_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='individuallessonentry',
            name='student_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='individualprice',
            name='basic_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='individualprice',
            name='effective_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='individualprice',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualprice',
            name='premium_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='individualprice',
            name='vacation_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollsheet',
            name='period_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payrollsheet',
            name='period_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payrollsheet',
            name='rejection_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payrollsheet',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_sheets', to='payroll.teacher'),
        ),
        migrations.AlterField(
            model_name='payrollsheet',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pkshprice',
            name='basic_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pkshprice',
            name='effective_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pkshprice',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pkshprice',
            name='premium_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='pkshprice',
            name='vacation_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('teacher', 'Педагог'), ('employee', 'Сотрудник'), ('administrator', 'Администратор'), ('accountant', 'Бухгалтер'), ('senior_admin', 'Старший администратор'), ('chief_admin', 'Главный администратор'), ('moderator', 'Модератор')], default='teacher', max_length=20, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=300)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название филиала')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Баланс')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='payroll.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='payroll.branch', verbose_name='Филиал'),
        ),
        migrations.CreateModel(
            name='BranchTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Внесение'), ('withdrawal', 'Снятие')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payroll.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакция филиала',
                'verbose_name_plural': 'Транзакции филиалов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
